import { TTSBackend } from './core/backend.js';
import { normalizeSettings,validateSettings,modelRules,NAMESPACE } from './core/state.js';
import { parseDialogue,renderDialogue,plainDialogue,promptPlan,validatePreset,isPlaceholderRole,DEFAULT_PROMPT,knownFormats } from './core/protocol.js';
import { FloatingPlayer } from './core/floating.js';
import { renderPictures, drawPromptPlan, withoutPictures } from './core/draw.js';
import { createPictureHost } from './host-pictures.js';
import { createChatHost } from './host-chat.js';
const base=new URL('.',import.meta.url),marker=globalThis.crypto?.randomUUID?.()||'unavailable';
let active=false,hooked=false,settings,cache,player,panel,frame,observer,renderTimer,floating,lineRaf,lineMedia,playbackMessage,selectedMessage,backend,enabling;
let renderEpoch=0,pictures=null,chats=null,pendingDraw=null;
const listeners=[],prompts=new Set();
const context=()=>globalThis.SillyTavern?.getContext();
// Generation interceptor (manifest generate_interceptor): picture blocks stay in the chat but are left out of the
// messages sent to the model, so old pictures do not cost tokens on every request. Replaced, never mutated.
globalThis.stIphonieInterceptor=function(chat){if(!active||settings?.draw?.strip===false)return;for(let i=0;i<chat.length;i++){const m=chat[i];if(typeof m?.mes==='string'&&/<img\b/i.test(m.mes))chat[i]={...m,mes:withoutPictures(m.mes)};}};
function notice(message){if(globalThis.toastr)globalThis.toastr.info(message,'ST-iPhonie');else console.info('[ST-iPhonie]',message);}
function formats(){return knownFormats(settings);}
function parsed(message){for(const format of formats()){try{const lines=parseDialogue(message,format);if(lines.length)return {format,lines};}catch{}}return {format:formats()[0],lines:[]};}
function clearPrompts(){const ctx=context();if(!ctx)return;for(const key of Object.keys(ctx.extensionPrompts||{})){if(key.startsWith('sttts.entry.'))ctx.setExtensionPrompt(key,'',-1,0);}prompts.clear();}
function inject(type,options,dryRun){clearPrompts();if(!active)return;for(const p of [...(voiceOn()?promptPlan(settings,modelRules(settings)):[]),...drawPromptPlan(settings),...(chats?.bringPlan(typeof type==='string'?type:'',dryRun===true)||[])]){context().setExtensionPrompt(p.key,p.text,p.position,p.depth,false,p.role);prompts.add(p.key);}}
function persist(next){return backend.save(next);}
const voiceOn=()=>settings?.general?.voiceEnabled!==false;
function storeSettings(next){const voiced=voiceOn();settings=next;context().extensionSettings[NAMESPACE]=structuredClone(next);context().saveSettingsDebounced();if(active){inject();syncFloating();if(voiced!==voiceOn()){player.stop();rerender();}else scheduleRender();}}
function currentMessage(id){const ctx=context(),message=ctx.chat[id];if(!message||message.is_user||message.is_system)return null;return {message,chat:ctx.getCurrentChatId?.()??ctx.chatId,id,raw:message.mes,swipe:message.swipe_id};}
function unchanged(snap){const now=currentMessage(snap.id);return active&&now?.message===snap.message&&now.chat===snap.chat&&now.raw===snap.raw&&now.swipe===snap.swipe;}
function playMessage(id,index){const snap=currentMessage(id);if(!snap)return;const current=player.queue[player.index];if(index!==undefined&&playbackMessage&&unchanged(playbackMessage)&&playbackMessage.id===id&&current?.uiIndex===index&&['playing','generating','paused'].includes(player.phase)){player.toggle();return;}selectedMessage=snap;playbackMessage=snap;const lines=parsed(snap.raw).lines.map((line,uiIndex)=>({...line,uiIndex}));player.start(index===undefined?lines:lines[index]?[lines[index]]:[],()=>unchanged(snap));}
function playSelected(){if(selectedMessage&&unchanged(selectedMessage))return playMessage(selectedMessage.id);const chat=context().chat;for(let id=chat.length-1;id>=0;id--){const snap=currentMessage(id);if(snap&&parsed(snap.raw).lines.length)return playMessage(id);}notice('当前聊天还没有可朗读的台词');}
function status(value){floating?.update(value);const label=document.querySelector('#sttts-extension-entry .sttts-status');if(label)label.textContent=value.message;const toggle=document.querySelector('#sttts-toggle');if(toggle){toggle.textContent=value.phase==='paused'?'继续':'暂停';toggle.disabled=!['playing','generating','paused'].includes(value.phase);}const stop=document.querySelector('#sttts-stop');if(stop)stop.disabled=['idle','error'].includes(value.phase);frame?.contentWindow?.stTtsUpdate?.(value);if(value.phase==='error'&&!panel?.open)notice(value.message);scheduleRender();}
// A reply whose voice lines were not turned into waves when it was first drawn (seen once after a generation) is redrawn once.
const healed=new Map(),streaming=()=>{const p=context()?.streamingProcessor;return !!p&&!p.isFinished;};
function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(decorate,40);}
function animateLines(){cancelAnimationFrame(lineRaf);document.querySelectorAll('[data-sttts-bar]').forEach(el=>el.style.removeProperty('transform'));if(!active||player.phase!=='playing'||!settings.general.waveformEnabled||lineMedia?.matches||document.hidden)return;let previous=0;const draw=now=>{if(now-previous>=32){const levels=player.sink.levels();document.querySelectorAll('[data-sttts-state="playing"] [data-sttts-bar]').forEach((bar,i)=>bar.style.transform='scaleY('+(.2+.8*(levels[i%5]||0))+')');previous=now;}lineRaf=requestAnimationFrame(draw);};lineRaf=requestAnimationFrame(draw);}
async function decorate(){if(!active)return;pictures?.decorate(currentMessage);const epoch=++renderEpoch,livePlayer=player;document.querySelectorAll('#chat [data-sttts-owned="toolbar"]').forEach(el=>el.remove());const jobs=[];for(const element of document.querySelectorAll('#chat .mes[mesid]')){const id=Number(element.getAttribute('mesid')),snap=currentMessage(id);if(!snap)continue;const lines=parsed(snap.raw).lines;if(voiceOn()&&lines.length&&!element.querySelector('[data-sttts-line]')&&!streaming()&&healed.get(id)!==snap.raw){healed.set(id,snap.raw);context().updateMessageBlock?.(id,snap.message);continue;}for(const button of element.querySelectorAll('[data-sttts-action="line"]')){const owner=button.closest('[data-sttts-token]'),index=Number(owner?.dataset.stttsLine),line=lines[index];if(owner?.dataset.stttsToken!==marker||!line)continue;jobs.push((async()=>{let state=await livePlayer.lineState(line);const route=settings.routes.find(r=>r.name===line.role);if(state==='ungenerated'&&!route?.voice)state='unbound';if(epoch!==renderEpoch||!active||livePlayer!==player||!unchanged(snap)||!button.isConnected)return;const current=player.queue[player.index];if(playbackMessage&&unchanged(playbackMessage)&&playbackMessage.id===id&&current?.uiIndex===index&&['playing','generating','paused','waiting'].includes(player.phase))state=player.phase;button.dataset.stttsState=state;const labels={unbound:'还没有配音，点击选择音色',ungenerated:'未生成，点击生成并播放',ready:'可以播放',played:'已播放，点击再次朗读',generating:'正在生成，点击暂停',playing:'正在播放，点击暂停',paused:'已暂停，点击继续',waiting:'等待选择音色'};button.title=labels[state];button.setAttribute('aria-label',line.role+'：'+labels[state]);button.setAttribute('aria-busy',String(state==='generating'));})());}}
await Promise.all(jobs);if(epoch===renderEpoch&&active)animateLines();}
function rerender(){const ctx=context();document.querySelectorAll('#chat .mes[mesid]').forEach(el=>{const id=Number(el.getAttribute('mesid'));if(ctx.chat[id])ctx.updateMessageBlock(id,ctx.chat[id]);});scheduleRender();}
function unknown(name){if(isPlaceholderRole(name)){player.stop('请在台词中填写实际角色名');return;}let route=settings.routes.find(r=>r.name===name);if(!route){route={id:crypto.randomUUID(),name,engine:'fish',voice:'',language:''};settings.routes.push(route);}settings.selected=route.id;persist(settings);openPanel(route.id);}
function openPanel(roleId){floating?.setMode('docked');if(!panel){panel=document.createElement('dialog');panel.id='sttts-panel';panel.setAttribute('aria-label','ST-iPhonie');frame=document.createElement('iframe');frame.title='ST-iPhonie';frame.src=new URL('ui/index.html',base).href;panel.append(frame);panel.addEventListener('close',()=>frame?.contentWindow?.stTtsPanelVisibility?.(false));panel.addEventListener('cancel',()=>{if(['playing','generating'].includes(player.phase))player.toggle();});document.body.append(panel);}if(!panel.open){panel.showModal();frame.contentWindow?.stTtsPanelVisibility?.(true);}if(roleId)frame.contentWindow?.stTtsOpenRole?.(roleId);}
function connect(source){
 if(!active||source!==frame?.contentWindow)throw Error('设置页面未连接');
 const owner=backend,api=owner.api();
 const check=()=>{if(!active||backend!==owner||owner.closed||source!==frame?.contentWindow)throw Error('设置页面已失效，请重新打开');};
 return Object.freeze({...api,
  save:(next,revision)=>{check();return api.save({...next,floating:settings.floating},revision);},
  close:()=>{check();panel?.close();},
  latest:()=>{check();const ctx=context();for(let i=ctx.chat.length-1;i>=0;i--){const snap=currentMessage(i);if(snap&&parsed(snap.raw).lines.length)return {id:i,lines:parsed(snap.raw).lines};}return {id:-1,lines:[]};},
  play:(id,line)=>{check();playMessage(id,line);},
  audition:route=>{check();playbackMessage=null;api.audition(route);},
  recentMessages:()=>{check();return pictures.recentMessages();},
  insertImage:(id,photoId)=>{check();return pictures.insertImage(id,photoId);},
  suggestPrompt:()=>{check();return pictures.suggestPrompt();},
  chatPictureStats:()=>{check();return pictures.pictureStats();},
  planLatestPictures:()=>{check();return pictures.planLatest();},
  clearChatPictures:()=>{check();return pictures.clearPictures();},
  takeDraw:()=>{check();const value=pendingDraw;pendingDraw=null;return value;},
  chatReply:threadId=>{check();return chats.reply(threadId);},
  chatBring:(threadId,ids)=>{check();return chats.bring(threadId,ids);},
  chatPendingBring:()=>{check();return chats.pendingBring();},
  chatCancelBring:()=>{check();chats.cancelBring();},
  chatTyping:threadId=>{check();return chats.typing(threadId);},
  playFavorite:id=>{check();playbackMessage=null;return api.playFavorite(id);}
 });
}
function click(event){if(active&&pictures?.click(event))return;const button=event.target.closest('[data-sttts-action]');if(!button||!active)return;const owner=button.closest('[data-sttts-token]');if(owner?.dataset.stttsToken!==marker)return;event.preventDefault();const action=button.dataset.stttsAction,id=Number(button.closest('.mes[mesid]')?.getAttribute('mesid'));if(action==='settings')openPanel();else if(action==='stop')player.stop();else if(action==='toggle')player.toggle();else if(action==='all')playMessage(id);else if(action==='line')playMessage(id,Number(owner.dataset.stttsLine));}
function mountEntry(){const mount=document.querySelector('#extensions_settings');if(!mount)return;const entry=document.createElement('div');entry.id='sttts-extension-entry';entry.innerHTML='<div class="inline-drawer"><div class="inline-drawer-toggle inline-drawer-header" id="sttts-entry-header" tabindex="0"><b>ST-iPhonie</b><div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div></div><div class="inline-drawer-content"><div class="sttts-entry-controls"><button type="button" id="sttts-all" class="menu_button">整条播放</button><button type="button" id="sttts-toggle" class="menu_button" disabled>暂停</button><button type="button" id="sttts-stop" class="menu_button" disabled>停止</button></div><span class="sttts-status" role="status">等待播放</span><button type="button" id="sttts-open" class="menu_button">打开小手机</button></div></div>';entry.querySelector('#sttts-all').addEventListener('click',playSelected);entry.querySelector('#sttts-toggle').addEventListener('click',()=>player.toggle());entry.querySelector('#sttts-stop').addEventListener('click',()=>player.stop());entry.querySelector('#sttts-open').addEventListener('click',()=>openPanel());entry.querySelector('#sttts-entry-header').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.currentTarget.click();}});mount.append(entry);}
function syncFloating(){if(!active)return;if(!settings.general.floatingEnabled){floating?.destroy();floating=null;return;}if(floating){floating.applyTheme();floating.animate();return;}floating=new FloatingPlayer({openSettings:()=>openPanel(),position:settings.floating,savePosition:p=>{settings.floating=p;persist(settings);},levels:()=>player.sink.levels(),theme:()=>settings.theme,motion:()=>settings.general.waveformEnabled});floating.update({phase:player.phase,message:player.message,engine:player.engine,speaker:player.speaker});}
async function enableInternal(){if(active)return;const ctx=context();if(!ctx?.setExtensionPrompt||!ctx.messageFormatter?.addHook||!ctx.updateMessageBlock||!ctx.eventSource?.on||!ctx.eventSource?.removeListener||!ctx.eventTypes||!ctx.extensionSettings||!ctx.saveSettingsDebounced){notice('ST-iPhonie 需要支持消息格式钩子的 SillyTavern 1.19 或更新版本');return;}if(!globalThis.crypto?.subtle||!globalThis.crypto?.randomUUID){notice('请用 localhost 或 HTTPS 地址打开酒馆，以启用语音缓存和设置');return;}if(!globalThis.AudioContext||!globalThis.AbortSignal?.any){notice('当前浏览器缺少语音播放所需功能，请更新浏览器');return;}backend=new TTSBackend({settings:ctx.extensionSettings[NAMESPACE],persist:storeSettings,notify:notice,change:status,unknown});settings=backend.settings;cache=backend.cache;player=backend.player;pictures=createPictureHost({context,settings:()=>settings,backend,marker,scheduleRender,notice,openDraw:payload=>{pendingDraw=payload;openPanel();frame?.contentWindow?.stTtsOpenDraw?.();}});chats=createChatHost({context,settings:()=>settings,backend,notice});await backend.initialize();ctx.extensionSettings[NAMESPACE]=structuredClone(settings);ctx.saveSettingsDebounced();active=true;lineMedia=matchMedia('(prefers-reduced-motion: reduce)');lineMedia.addEventListener('change',animateLines);document.addEventListener('visibilitychange',animateLines);globalThis.__stTtsPanelBridge={connect};
 if(!hooked){ctx.messageFormatter.addHook((text,meta)=>{if(!active||meta.isUser||meta.isSystem||meta.isReasoning||meta.messageId<0)return text;try{const out=renderPictures(text,marker);const p=parsed(out);return p.lines.length?(voiceOn()?renderDialogue(out,p.format,marker):plainDialogue(out,p.format)):out;}catch{return text;}},{stage:ctx.messageFormatter.stage.BEFORE_REGEX,order:100});hooked=true;}
 const subscribe=(name,fn)=>{if(!name)return;ctx.eventSource.on(name,fn);listeners.push([ctx.eventSource,name,fn]);};subscribe(ctx.eventTypes.GENERATION_AFTER_COMMANDS,inject);
 for(const event of ['CHAT_CHANGED','MESSAGE_SWIPED','MESSAGE_EDITED','MESSAGE_DELETED'])subscribe(ctx.eventTypes[event],()=>{player.stop('消息已变化');scheduleRender();});for(const event of ['CHARACTER_MESSAGE_RENDERED','MESSAGE_RECEIVED'])subscribe(ctx.eventTypes[event],scheduleRender);subscribe(ctx.eventTypes.CHARACTER_MESSAGE_RENDERED,id=>{pictures?.autoPictures(Number(id)).catch(e=>notice(e.message));});
 document.addEventListener('click',click);mountEntry();syncFloating();observer=new MutationObserver(scheduleRender);const chat=document.querySelector('#chat');if(chat)observer.observe(chat,{childList:true,subtree:true});inject();rerender();}
export function enable(){if(enabling)return enabling;enabling=enableInternal().finally(()=>{enabling=null;});return enabling;}
export async function disable(){if(enabling)await enabling;if(!active)return;active=false;renderEpoch++;cancelAnimationFrame(lineRaf);lineMedia?.removeEventListener('change',animateLines);document.removeEventListener('visibilitychange',animateLines);playbackMessage=selectedMessage=null;healed.clear();player.stop();clearPrompts();for(const [source,event,fn] of listeners)source.removeListener(event,fn);listeners.length=0;observer?.disconnect();clearTimeout(renderTimer);document.removeEventListener('click',click);document.querySelector('#sttts-extension-entry')?.remove();floating?.destroy();floating=null;document.querySelectorAll('[data-sttts-owned="toolbar"]').forEach(el=>el.remove());panel?.remove();panel=frame=null;delete globalThis.__stTtsPanelBridge;pictures=null;chats=null;pendingDraw=null;await backend.close();rerender();}
export const dispose=disable;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>enable().catch(e=>notice(e.message)),{once:true});else enable().catch(e=>notice(e.message));
