import { normalizeSettings,validateSettings,modelRules,NAMESPACE } from './core/state.js';
import { parseDialogue,renderDialogue,promptPlan,validatePreset } from './core/protocol.js';
import { Providers } from './core/providers.js';
import { AudioCache } from './core/cache.js';
import { DialoguePlayer } from './core/player.js';
import { FloatingPlayer } from './core/floating.js';
const base=new URL('.',import.meta.url),marker=globalThis.crypto?.randomUUID?.()||'unavailable';
let active=false,hooked=false,settings,cache,player,panel,frame,observer,renderTimer,floating;
const providers=new Providers(),listeners=[],prompts=new Set();
const context=()=>globalThis.SillyTavern?.getContext();
function notice(message){if(globalThis.toastr)globalThis.toastr.info(message,'ST-TTS');else console.info('[ST-TTS]',message);}
function formats(){const p=settings.presets.find(p=>p.id===settings.activePreset);return [...new Set([p?.format,...settings.presets.map(p=>p.format)].filter(Boolean))];}
function parsed(message){for(const format of formats()){try{const lines=parseDialogue(message,format);if(lines.length)return {format,lines};}catch{}}return {format:formats()[0],lines:[]};}
function clearPrompts(){const ctx=context();if(!ctx)return;for(const key of Object.keys(ctx.extensionPrompts||{})){if(key.startsWith('sttts.entry.'))ctx.setExtensionPrompt(key,'',-1,0);}prompts.clear();}
function inject(){clearPrompts();if(!active)return;for(const p of promptPlan(settings,modelRules(settings))){context().setExtensionPrompt(p.key,p.text,p.position,p.depth,false,p.role);prompts.add(p.key);}}
function persist(next){const copy=normalizeSettings(next);copy.scope=settings.scope;validateSettings(copy);settings=copy;context().extensionSettings[NAMESPACE]=structuredClone(settings);context().saveSettingsDebounced();inject();syncFloating();scheduleRender();return structuredClone(settings);}
function currentMessage(id){const ctx=context(),message=ctx.chat[id];if(!message||message.is_user||message.is_system)return null;return {message,chat:ctx.getCurrentChatId?.()??ctx.chatId,id,raw:message.mes,swipe:message.swipe_id};}
function unchanged(snap){const now=currentMessage(snap.id);return active&&now?.message===snap.message&&now.chat===snap.chat&&now.raw===snap.raw&&now.swipe===snap.swipe;}
function playMessage(id,index){const snap=currentMessage(id);if(!snap)return;const lines=parsed(snap.raw).lines;player.start(index===undefined?lines:lines[index]?[lines[index]]:[],()=>unchanged(snap));}
function status(value){floating?.update(value);document.querySelectorAll('[data-sttts-owned="toolbar"] .sttts-status').forEach(el=>el.textContent=value.message);frame?.contentWindow?.stTtsUpdate?.(value);}
function scheduleRender(){clearTimeout(renderTimer);renderTimer=setTimeout(decorate,40);}
function decorate(){if(!active)return;document.querySelectorAll('#chat .mes[mesid]').forEach(element=>{const id=Number(element.getAttribute('mesid')),snap=currentMessage(id),existing=element.querySelector('[data-sttts-owned="toolbar"]');if(!snap||!parsed(snap.raw).lines.length){existing?.remove();return;}if(existing)return;const bar=document.createElement('div');bar.className='sttts-toolbar';bar.dataset.stttsOwned='toolbar';bar.dataset.stttsToken=marker;for(const [action,text] of [['all','整条播放'],['toggle','暂停 / 继续'],['stop','停止'],['settings','配音设置']]){const button=document.createElement('button');button.type='button';button.dataset.stttsAction=action;button.textContent=text;bar.append(button);}const label=document.createElement('span');label.className='sttts-status';label.role='status';bar.append(label);(element.querySelector('.mes_text')||element).append(bar);});}
function rerender(){const ctx=context();document.querySelectorAll('#chat .mes[mesid]').forEach(el=>{const id=Number(el.getAttribute('mesid'));if(ctx.chat[id])ctx.updateMessageBlock(id,ctx.chat[id]);});scheduleRender();}
function unknown(name){let route=settings.routes.find(r=>r.name===name);if(!route){route={id:crypto.randomUUID(),name,engine:'fish',voice:'',language:''};settings.routes.push(route);}settings.selected=route.id;persist(settings);openPanel(route.id);}
function openPanel(roleId){floating?.setMode('docked');if(!panel){panel=document.createElement('dialog');panel.id='sttts-panel';panel.setAttribute('aria-label','ST-TTS 设置');frame=document.createElement('iframe');frame.title='角色对白设置';frame.src=new URL('ui/index.html',base).href;panel.append(frame);panel.addEventListener('cancel',()=>{if(['playing','generating'].includes(player.phase))player.toggle();});document.body.append(panel);}if(!panel.open)panel.showModal();if(roleId)frame.contentWindow?.stTtsOpenRole?.(roleId);}
async function fileReference(file){if(!file||file.size>20*1024*1024||file.size===0)throw Error('参考音频需为 0–20 MB 的文件');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const id=crypto.randomUUID()+':'+file.name;providers.references.set(id,btoa(binary));return id;}
function connect(source){if(!active||source!==frame?.contentWindow)throw Error('设置页面未连接');return Object.freeze({
 getState:()=>structuredClone(settings),save:next=>persist({...next,floating:settings.floating}),validatePreset:p=>{try{validatePreset(p);return '';}catch(e){return e.message;}},
 keyStatus:engine=>providers.keys.has(engine),setKey:(engine,key)=>providers.setKey(engine,key),reference:fileReference,
 voices:(engine,c,query)=>providers.voices(engine,c,query),cacheStats:()=>cache.stats(),
 clearCache:async()=>{player.stop('缓存已清理');await cache.clear();return cache.stats();},
 pendingRole:()=>player.pending,stop:()=>player.stop(),resume:()=>player.continuePending(),
 audition:route=>{const previous=settings;const temporary=structuredClone(settings);temporary.routes=temporary.routes.filter(r=>r.name!==route.name);temporary.routes.push(route);player.settings=()=>temporary;player.start([{role:route.name,emotion:'calm',text:({zh:'雨还没停，再坐一会儿吧。',en:'The rain has not stopped. Stay a little longer.',ja:'雨はまだ止んでいません。もう少しここにいましょう。',ko:'비가 아직 그치지 않았어요.'})[route.language||settings.general.defaultLanguage]||'Hello.'}],()=>active&&settings===previous);player.settings=()=>settings;},
 close:()=>panel.close(),status:()=>({phase:player.phase,message:player.message,index:player.index,total:player.queue.length}),latest:()=>{const ctx=context();for(let i=ctx.chat.length-1;i>=0;i--){const snap=currentMessage(i);if(snap&&parsed(snap.raw).lines.length)return {id:i,lines:parsed(snap.raw).lines};}return {id:-1,lines:[]};},play:(id,line)=>playMessage(id,line),toggle:()=>player.toggle()
 });}
function click(event){const button=event.target.closest('[data-sttts-action]');if(!button||!active)return;const owner=button.closest('[data-sttts-token]');if(owner?.dataset.stttsToken!==marker)return;event.preventDefault();const action=button.dataset.stttsAction,id=Number(button.closest('.mes[mesid]')?.getAttribute('mesid'));if(action==='settings')openPanel();else if(action==='stop')player.stop();else if(action==='toggle')player.toggle();else if(action==='all')playMessage(id);else if(action==='line')playMessage(id,Number(owner.dataset.stttsLine));}
function mountEntry(){const mount=document.querySelector('#extensions_settings');if(!mount)return;const entry=document.createElement('div');entry.id='sttts-extension-entry';entry.innerHTML='<div class="inline-drawer"><div class="inline-drawer-toggle inline-drawer-header" id="sttts-entry-header" tabindex="0"><b>ST-TTS · 角色对白</b><div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div></div><div class="inline-drawer-content"><button type="button" id="sttts-open" class="menu_button">打开配音设置</button></div></div>';entry.querySelector('#sttts-open').addEventListener('click',()=>openPanel());entry.querySelector('#sttts-entry-header').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.currentTarget.click();}});mount.append(entry);}
function syncFloating(){if(!active)return;if(!settings.general.floatingEnabled){floating?.destroy();floating=null;return;}if(floating){floating.applyTheme();floating.animate();return;}floating=new FloatingPlayer({openSettings:()=>openPanel(),playLatest:()=>{const chat=context().chat;for(let i=chat.length-1;i>=0;i--){const snap=currentMessage(i);if(snap&&parsed(snap.raw).lines.length){playMessage(i);return;}}status({phase:'idle',message:'当前聊天还没有可朗读的台词'});},toggle:()=>player.toggle(),stop:()=>player.stop(),position:settings.floating,savePosition:p=>{settings.floating=p;persist(settings);},levels:()=>player.sink.levels(),theme:()=>settings.theme,motion:()=>settings.general.waveformEnabled});floating.update({phase:player.phase,message:player.message,engine:player.engine,speaker:player.speaker});}
export async function enable(){if(active)return;const ctx=context();if(!ctx?.setExtensionPrompt||!ctx.messageFormatter?.addHook||!ctx.updateMessageBlock||!ctx.eventSource?.on||!ctx.eventSource?.removeListener||!ctx.eventTypes||!ctx.extensionSettings||!ctx.saveSettingsDebounced){notice('ST-TTS 需要支持消息格式钩子的 SillyTavern 1.19 或更新版本');return;}if(!globalThis.crypto?.subtle||!globalThis.crypto?.randomUUID){notice('请用 localhost 或 HTTPS 地址打开酒馆，以启用语音缓存和设置');return;}if(!globalThis.AudioContext||!globalThis.AbortSignal?.any){notice('当前浏览器缺少语音播放所需功能，请更新浏览器');return;}settings=normalizeSettings(ctx.extensionSettings[NAMESPACE]);validateSettings(settings);ctx.extensionSettings[NAMESPACE]=structuredClone(settings);ctx.saveSettingsDebounced();active=true;cache=new AudioCache(settings.scope,notice);player=new DialoguePlayer({settings:()=>settings,providers,cache,change:status,unknown});globalThis.__stTtsPanelBridge={connect};
 if(!hooked){ctx.messageFormatter.addHook((text,meta)=>{if(!active||meta.isUser||meta.isSystem||meta.isReasoning||meta.messageId<0)return text;try{const p=parsed(text);return p.lines.length?renderDialogue(text,p.format,marker):text;}catch{return text;}},{stage:ctx.messageFormatter.stage.BEFORE_REGEX,order:100});hooked=true;}
 const subscribe=(name,fn)=>{if(!name)return;ctx.eventSource.on(name,fn);listeners.push([ctx.eventSource,name,fn]);};subscribe(ctx.eventTypes.GENERATION_AFTER_COMMANDS,inject);
 for(const event of ['CHAT_CHANGED','MESSAGE_SWIPED','MESSAGE_EDITED','MESSAGE_DELETED'])subscribe(ctx.eventTypes[event],()=>{player.stop('消息已变化');scheduleRender();});for(const event of ['CHARACTER_MESSAGE_RENDERED','MESSAGE_RECEIVED'])subscribe(ctx.eventTypes[event],scheduleRender);
 document.addEventListener('click',click);mountEntry();syncFloating();observer=new MutationObserver(scheduleRender);const chat=document.querySelector('#chat');if(chat)observer.observe(chat,{childList:true,subtree:true});inject();rerender();}
export async function disable(){if(!active)return;active=false;player.stop();player.sink.close();providers.clear();clearPrompts();for(const [source,event,fn] of listeners)source.removeListener(event,fn);listeners.length=0;observer?.disconnect();clearTimeout(renderTimer);document.removeEventListener('click',click);document.querySelector('#sttts-extension-entry')?.remove();floating?.destroy();floating=null;document.querySelectorAll('[data-sttts-owned="toolbar"]').forEach(el=>el.remove());panel?.remove();panel=frame=null;delete globalThis.__stTtsPanelBridge;await cache.close();rerender();}
export const dispose=disable;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>enable().catch(e=>notice(e.message)),{once:true});else enable().catch(e=>notice(e.message));
