const WAVE='<svg viewBox="0 0 32 32" aria-hidden="true"><g class="wave"><rect x="4" y="11" width="3" height="10" rx="1.5"/><rect x="9.25" y="6.5" width="3" height="19" rx="1.5"/><rect x="14.5" y="3" width="3" height="26" rx="1.5"/><rect x="19.75" y="8" width="3" height="16" rx="1.5"/><rect x="25" y="12" width="3" height="8" rx="1.5"/></g></svg>';
export class FloatingPlayer{
 constructor({openSettings,position,savePosition,levels,theme,motion}){Object.assign(this,{openSettings,savePosition,levels,theme,motion});this.side=position?.side==='left'?'left':'right';this.y=Number.isFinite(position?.y)?Math.max(0,Math.min(1,position.y)):.58;this.phase='idle';this.mode='rest';this.root=document.createElement('div');this.root.id='sttts-floating';this.shadow=this.root.attachShadow({mode:'open'});this.shadow.innerHTML=`<link rel="stylesheet" href="${new URL('../floating.css',import.meta.url).href}"><div class="float" data-side="${this.side}" data-mode="rest" data-phase="idle" data-engine="fish"><button class="orb" type="button" aria-label="打开 ST-TTS 设置，可拖动"><span class="orb-rim"></span><span class="orb-face">${WAVE}</span><span class="edge-mark"></span><span class="engine-dot"></span></button></div>`;
 this.box=this.shadow.querySelector('.float');this.orb=this.shadow.querySelector('.orb');this.bars=[...this.shadow.querySelectorAll('.wave rect')];this.abort=new AbortController();const opts={signal:this.abort.signal};document.body.append(this.root);this.reduced=matchMedia('(prefers-reduced-motion: reduce)');this.colorScheme=matchMedia('(prefers-color-scheme: dark)');this.colorScheme.addEventListener('change',()=>this.applyTheme(),opts);this.reduced.addEventListener('change',()=>this.animate(),opts);
 this.box.addEventListener('click',e=>{if(e.target===this.box&&this.mode==='docked')this.activate();},opts);
 this.orb.addEventListener('pointerdown',e=>this.down(e),opts);this.orb.addEventListener('pointermove',e=>this.move(e),opts);this.orb.addEventListener('pointerup',e=>this.up(e),opts);this.orb.addEventListener('pointercancel',()=>this.cancelDrag(),opts);this.orb.addEventListener('click',()=>this.activate(),opts);
 this.root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();this.setMode('docked');this.orb.focus({preventScroll:true});}},opts);window.addEventListener('resize',()=>this.place(),opts);window.visualViewport?.addEventListener('resize',()=>this.place(),opts);document.addEventListener('visibilitychange',()=>this.animate(),opts);this.place();this.applyTheme();this.arm();
 }
 applyTheme(){const theme=this.theme();this.box.dataset.theme=theme==='dark'||theme==='system'&&this.colorScheme.matches?'dark':'light';}
 place(){const height=window.visualViewport?.height||innerHeight;const top=24+this.y*Math.max(0,height-136);this.root.style.top=Math.round(top)+'px';this.root.style.left=this.side==='left'?'8px':'auto';this.root.style.right=this.side==='right'?'8px':'auto';this.box.dataset.side=this.side;}
 arm(){clearTimeout(this.timer);if(this.mode==='rest')this.timer=setTimeout(()=>{if(this.mode==='rest'&&!this.drag&&!this.orb.matches(':focus-visible'))this.setMode('docked');},3200);}
 activate(){if(Date.now()-(this.lastDrag||0)<400)return;if(this.mode==='docked'){this.setMode('rest');return;}this.setMode('docked');this.openSettings();}
 setMode(mode){this.mode=mode==='docked'?'docked':'rest';this.box.dataset.mode=this.mode;const label=this.mode==='docked'?'展开 ST-TTS 悬浮球':'打开 ST-TTS 设置，可拖动';this.orb.setAttribute('aria-label',label);this.orb.title=this.mode==='docked'?label:this.message||label;this.arm();}
 down(e){if(e.button!==0)return;clearTimeout(this.timer);const rect=this.root.getBoundingClientRect();this.drag={x:e.clientX,y:e.clientY,left:rect.left,top:rect.top,moved:false,pointer:e.pointerId};this.orb.setPointerCapture(e.pointerId);}
 move(e){const d=this.drag;if(!d||d.pointer!==e.pointerId)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(!d.moved&&Math.hypot(dx,dy)<6)return;d.moved=true;this.box.dataset.dragging='true';this.box.dataset.mode='rest';const h=window.visualViewport?.height||innerHeight;this.root.style.left=Math.min(innerWidth-62,Math.max(2,d.left+dx))+'px';this.root.style.right='auto';this.root.style.top=Math.min(h-76,Math.max(20,d.top+dy))+'px';}
 up(e){const d=this.drag;if(!d||d.pointer!==e.pointerId)return;if(d.moved){this.lastDrag=Date.now();const rect=this.root.getBoundingClientRect(),h=window.visualViewport?.height||innerHeight;this.side=rect.left+30<innerWidth/2?'left':'right';this.y=Math.max(0,Math.min(1,(rect.top-24)/Math.max(1,h-136)));this.place();this.savePosition({side:this.side,y:this.y});this.setMode('rest');}this.drag=null;delete this.box.dataset.dragging;this.orb.releasePointerCapture(e.pointerId);this.arm();}
 cancelDrag(){this.drag=null;delete this.box.dataset.dragging;this.place();this.setMode('rest');}
 update(value){this.phase=value.phase;this.box.dataset.phase=value.phase;if(value.engine)this.box.dataset.engine=value.engine;this.message=value.message;this.orb.title=this.mode==='docked'?'展开 ST-TTS 悬浮球':value.message||'打开 ST-TTS 设置';this.applyTheme();this.animate();}
 animate(){cancelAnimationFrame(this.raf);this.bars.forEach(b=>b.style.removeProperty('transform'));if(this.phase!=='playing'||!this.motion()||this.reduced.matches||document.hidden)return;let previous=0;const draw=now=>{if(now-previous>=32){const values=this.levels?.()||[];this.bars.forEach((b,i)=>{b.style.transform='scaleY('+(.18+.82*(values[i]||0))+')';});previous=now;}this.raf=requestAnimationFrame(draw);};this.raf=requestAnimationFrame(draw);}
 destroy(){this.abort.abort();clearTimeout(this.timer);cancelAnimationFrame(this.raf);this.root.remove();}
}
