const WAVE='<svg viewBox="0 0 32 32" aria-hidden="true"><g class="wave"><rect x="4" y="11" width="3" height="10" rx="1.5"/><rect x="9.25" y="6.5" width="3" height="19" rx="1.5"/><rect x="14.5" y="3" width="3" height="26" rx="1.5"/><rect x="19.75" y="8" width="3" height="16" rx="1.5"/><rect x="25" y="12" width="3" height="8" rx="1.5"/></g></svg>';
const PLAY='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 10 7-10 7Z"/></svg>';
const PAUSE='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14M16 5v14"/></svg>';
const STOP='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="6" y="6" width="12" height="12" rx="2"/></svg>';
export class FloatingPlayer{
 constructor({openSettings,playLatest,toggle,stop,position,savePosition,levels,theme,motion}){Object.assign(this,{openSettings,playLatest,toggle,stop,savePosition,levels,theme,motion});this.side=position?.side==='left'?'left':'right';this.y=Number.isFinite(position?.y)?Math.max(0,Math.min(1,position.y)):.58;this.phase='idle';this.mode='rest';this.root=document.createElement('div');this.root.id='sttts-floating';this.shadow=this.root.attachShadow({mode:'open'});this.shadow.innerHTML=`<link rel="stylesheet" href="${new URL('../floating.css',import.meta.url).href}"><div class="float" data-side="${this.side}" data-mode="rest" data-phase="idle" data-engine="fish"><button class="orb" type="button" aria-label="打开 ST-TTS 播放器，可拖动" aria-expanded="false" aria-controls="controls"><span class="orb-rim"></span><span class="orb-face">${WAVE}</span><span class="edge-mark"></span><span class="engine-dot"></span></button><section class="controls" id="controls" aria-label="语音播放控制" hidden><div class="top"><span class="brand">ST-TTS <span>角色对白</span></span><button class="close" type="button" aria-label="收起播放器"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m7 7 10 10M17 7 7 17"/></svg></button></div><div class="track"><span class="track-dot"></span><strong class="speaker">听见这一刻</strong><span class="engine"></span></div><p class="status" role="status">点击播放最新回复</p><div class="actions"><button class="main-play" type="button" aria-label="播放最新回复">${PLAY}<span>播放</span></button><button class="stop" type="button" aria-label="停止播放" disabled>${STOP}</button><button class="settings" type="button">配音设置<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg></button></div></section></div>`;
 this.box=this.shadow.querySelector('.float');this.orb=this.shadow.querySelector('.orb');this.controls=this.shadow.querySelector('.controls');this.bars=[...this.shadow.querySelectorAll('.wave rect')];this.abort=new AbortController();const opts={signal:this.abort.signal};document.body.append(this.root);this.reduced=matchMedia('(prefers-reduced-motion: reduce)');this.colorScheme=matchMedia('(prefers-color-scheme: dark)');this.colorScheme.addEventListener('change',()=>this.applyTheme(),opts);this.reduced.addEventListener('change',()=>this.animate(),opts);
 this.box.addEventListener('click',e=>{if(e.target===this.box&&this.mode==='docked')this.setMode('open');},opts);
 this.orb.addEventListener('pointerdown',e=>this.down(e),opts);this.orb.addEventListener('pointermove',e=>this.move(e),opts);this.orb.addEventListener('pointerup',e=>this.up(e),opts);this.orb.addEventListener('pointercancel',()=>this.cancelDrag(),opts);this.orb.addEventListener('click',()=>{if(Date.now()-(this.lastDrag||0)<400)return;this.setMode(this.mode==='open'?'rest':'open');},opts);
 this.shadow.querySelector('.close').addEventListener('click',()=>{this.setMode('docked');this.orb.focus({preventScroll:true});},opts);this.shadow.querySelector('.settings').addEventListener('click',()=>{this.setMode('docked');this.openSettings();},opts);this.shadow.querySelector('.stop').addEventListener('click',()=>this.stop(),opts);this.shadow.querySelector('.main-play').addEventListener('click',()=>{if(['playing','generating','paused'].includes(this.phase))this.toggle();else if(this.phase==='waiting')this.openSettings();else this.playLatest();},opts);
 this.root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();this.setMode('docked');this.orb.focus({preventScroll:true});}},opts);document.addEventListener('pointerdown',e=>{if(!e.composedPath().includes(this.root)&&this.mode==='open')this.setMode('docked');},opts);window.addEventListener('resize',()=>this.place(),opts);window.visualViewport?.addEventListener('resize',()=>this.place(),opts);document.addEventListener('visibilitychange',()=>this.animate(),opts);this.place();this.applyTheme();this.arm();
 }
 applyTheme(){const theme=this.theme();this.box.dataset.theme=theme==='dark'||theme==='system'&&this.colorScheme.matches?'dark':'light';}
 place(){const height=window.visualViewport?.height||innerHeight;const top=24+this.y*Math.max(0,height-136);this.root.style.top=Math.round(top)+'px';this.root.style.left=this.side==='left'?'8px':'auto';this.root.style.right=this.side==='right'?'8px':'auto';this.box.dataset.side=this.side;this.controls.style.setProperty('--panel-shift',top>height-255?'-150px':'-16px');}
 arm(){clearTimeout(this.timer);if(this.mode==='rest')this.timer=setTimeout(()=>{if(this.mode==='rest'&&!this.drag&&!this.orb.matches(':focus-visible'))this.setMode('docked');},3200);}
 setMode(mode){this.mode=mode;this.box.dataset.mode=mode;this.orb.setAttribute('aria-expanded',String(mode==='open'));this.orb.setAttribute('aria-label',mode==='docked'?'展开 ST-TTS 播放器':'打开 ST-TTS 播放器，可拖动');this.controls.hidden=mode!=='open';this.arm();}
 down(e){if(e.button!==0)return;clearTimeout(this.timer);const rect=this.root.getBoundingClientRect();this.drag={x:e.clientX,y:e.clientY,left:rect.left,top:rect.top,moved:false,pointer:e.pointerId};this.orb.setPointerCapture(e.pointerId);}
 move(e){const d=this.drag;if(!d||d.pointer!==e.pointerId)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(!d.moved&&Math.hypot(dx,dy)<6)return;d.moved=true;this.box.dataset.dragging='true';this.box.dataset.mode='rest';this.controls.hidden=true;const h=window.visualViewport?.height||innerHeight;this.root.style.left=Math.min(innerWidth-62,Math.max(2,d.left+dx))+'px';this.root.style.right='auto';this.root.style.top=Math.min(h-76,Math.max(20,d.top+dy))+'px';}
 up(e){const d=this.drag;if(!d||d.pointer!==e.pointerId)return;if(d.moved){this.lastDrag=Date.now();const rect=this.root.getBoundingClientRect(),h=window.visualViewport?.height||innerHeight;this.side=rect.left+30<innerWidth/2?'left':'right';this.y=Math.max(0,Math.min(1,(rect.top-24)/Math.max(1,h-136)));this.place();this.savePosition({side:this.side,y:this.y});this.setMode('rest');}this.drag=null;delete this.box.dataset.dragging;this.orb.releasePointerCapture(e.pointerId);this.arm();}
 cancelDrag(){this.drag=null;delete this.box.dataset.dragging;this.place();this.setMode('rest');}
 update(value){this.phase=value.phase;this.box.dataset.phase=value.phase;if(value.engine)this.box.dataset.engine=value.engine;this.shadow.querySelector('.speaker').textContent=value.speaker||'听见这一刻';this.shadow.querySelector('.engine').textContent=({fish:'Fish',mini:'MiniMax',eleven:'ElevenLabs'})[value.engine]||'';this.shadow.querySelector('.status').textContent=value.message||'点击播放最新回复';const action=this.shadow.querySelector('.main-play'),paused=['playing','generating'].includes(value.phase);action.innerHTML=(paused?PAUSE:PLAY)+'<span>'+(paused?'暂停':value.phase==='paused'?'继续':value.phase==='waiting'?'选择音色':'播放')+'</span>';action.setAttribute('aria-label',paused?'暂停播放':value.phase==='paused'?'继续播放':value.phase==='waiting'?'选择音色':'播放最新回复');this.shadow.querySelector('.stop').disabled=['idle','error'].includes(value.phase);this.applyTheme();this.animate();}
 animate(){cancelAnimationFrame(this.raf);this.bars.forEach(b=>b.style.removeProperty('transform'));if(this.phase!=='playing'||!this.motion()||this.reduced.matches||document.hidden)return;let previous=0;const draw=now=>{if(now-previous>=32){const values=this.levels?.()||[];this.bars.forEach((b,i)=>{b.style.transform='scaleY('+(.18+.82*(values[i]||0))+')';});previous=now;}this.raf=requestAnimationFrame(draw);};this.raf=requestAnimationFrame(draw);}
 destroy(){this.abort.abort();clearTimeout(this.timer);cancelAnimationFrame(this.raf);this.root.remove();}
}
