import { buildRequest } from './providers.js';
import { requestHash } from './cache.js';
export class BrowserAudio{
 constructor(){this.context=null;this.analyser=null;this.source=null;this.finish=null;}
 unlock(){this.context??=new AudioContext();if(!this.analyser){this.analyser=this.context.createAnalyser();this.analyser.fftSize=128;this.analyser.smoothingTimeConstant=.72;this.analyser.connect(this.context.destination);}return this.context.resume();}
 async play(blob,signal){const ctx=this.context;if(!ctx||ctx.state!=='running')throw Error('请再点一次播放，允许浏览器开启声音');let buffer;try{buffer=await ctx.decodeAudioData(await blob.arrayBuffer());}catch{throw Error('浏览器无法播放此音频格式，请在引擎配置改选 MP3 或 WAV');}signal.throwIfAborted();return new Promise((resolve,reject)=>{const source=ctx.createBufferSource();source.buffer=buffer;source.connect(this.analyser);this.source=source;const done=()=>{signal.removeEventListener('abort',abort);source.disconnect();if(this.source===source)this.source=null;resolve();};const abort=()=>{source.onended=null;try{source.stop();}catch{}source.disconnect();reject(new DOMException('已停止','AbortError'));};source.onended=done;signal.addEventListener('abort',abort,{once:true});source.start();});}
 levels(){if(!this.analyser)return [];const data=new Uint8Array(this.analyser.frequencyBinCount);this.analyser.getByteFrequencyData(data);return [0,1,2,3,4].map(i=>{let sum=0;for(let j=0;j<6;j++)sum+=data[i*6+j];return Math.min(1,Math.pow(sum/(6*255),.65));});}
 pause(){return this.context?.suspend();}
 resume(){return this.context?.resume();}
 stop(){if(this.source){this.source.onended=null;try{this.source.stop();}catch{}this.source.disconnect();this.source=null;}}
 close(){this.stop();this.context?.close();this.context=null;this.analyser=null;}
}
export class DialoguePlayer{
 constructor({settings,providers,cache,sink=new BrowserAudio(),change=()=>{},unknown=()=>{}}){Object.assign(this,{settings,providers,cache,sink,change,unknown});this.epoch=0;this.phase='idle';this.queue=[];this.index=0;this.pending=null;this.controller=null;this.valid=()=>true;this.played=new Set();}
 async lineState(line){try{const s=this.settings(),route=s.routes.find(r=>r.name===line.role);if(!route)return 'ungenerated';const request=buildRequest(route.engine,s.connections[route.engine],{...route,language:route.language||s.general.defaultLanguage},line,this.providers.references),key=await requestHash(request);if(this.played.has(key))return 'played';return s.general.cacheEnabled&&await this.cache.has(key)?'ready':'ungenerated';}catch{return 'ungenerated';}}
 emit(phase,message){this.phase=phase;this.message=message;this.change({phase,message,index:this.index,total:this.queue.length,engine:this.engine,speaker:this.speaker});}
 stop(message='已停止'){this.epoch++;this.controller?.abort();this.sink.stop();this.queue=[];this.pending=null;this.wake?.();this.wake=null;this.emit('idle',message);}
 start(lines,valid=()=>true,settingsOverride=null){this.stop();this.settingsOverride=settingsOverride;if(!lines.length)return;this.valid=valid;this.queue=lines;this.index=0;this.controller=new AbortController();this.unlockAndRun();}
 async run(epoch){const signal=this.controller.signal;try{while(this.index<this.queue.length){if(epoch!==this.epoch)return;if(!this.valid())return this.stop('消息已变化，请重新播放');const s=this.settingsOverride||this.settings(),line=this.queue[this.index],route=s.routes.find(r=>r.name===line.role);if(!route?.voice?.trim()&&!(route?.engine==='fish'&&s.connections.fish.params.references.length)&&!(route?.engine==='mini'&&s.connections.mini.params.timbre_weights.length)){this.speaker=line.role;this.engine='';this.pending=line.role;this.emit('waiting','等待为 '+line.role+' 选择音色');this.unknown(line.role);return;}this.pending=null;this.speaker=line.role;this.engine=route.engine;const effective={...route,language:route.language||s.general.defaultLanguage};const request=buildRequest(route.engine,s.connections[route.engine],effective,line,this.providers.references),key=await requestHash(request);if(epoch!==this.epoch)return;const cacheEpoch=this.cache.epoch;let blob=s.general.cacheEnabled?await this.cache.get(key):null;let fromCache=!!blob;this.emit(this.phase==='paused'?'paused':'generating',(fromCache?'读取缓存 · ':'正在生成 · ')+line.role);if(!blob){blob=await this.providers.synthesize(request,signal);if(epoch!==this.epoch)return;if(this.settings().general.cacheEnabled&&this.valid())await this.cache.put(key,blob,cacheEpoch);}if(epoch!==this.epoch)return;if(this.phase==='paused')await new Promise(resolve=>this.wake=resolve);if(epoch!==this.epoch)return;if(!this.valid())return this.stop('消息已变化，请重新播放');this.emit('playing','正在播放 · '+line.role+(fromCache?' · 缓存':''));await this.sink.play(blob,signal);if(epoch!==this.epoch)return;this.played.add(key);this.index++;}this.queue=[];this.emit('idle','播放完成');}catch(e){if(epoch!==this.epoch||signal.aborted)return;this.queue=[];this.pending=null;this.emit('error',e.message||'播放失败，请手动重试');}}
 toggle(){if(['playing','generating'].includes(this.phase)){this.resumePhase=this.phase;this.sink.pause();this.emit('paused','已暂停');}else if(this.phase==='paused'){const epoch=this.epoch;this.sink.resume().then(()=>{if(epoch!==this.epoch||this.phase!=='paused')return;this.emit(this.resumePhase==='generating'?'generating':'playing',this.resumePhase==='generating'?'继续生成':'继续播放');this.wake?.();this.wake=null;}).catch(e=>{if(epoch===this.epoch)this.emit('error',e.message||'请再次点击以开启声音');});}}
 unlockAndRun(){const epoch=this.epoch;this.sink.unlock().then(()=>{if(epoch===this.epoch)this.run(epoch);}).catch(e=>{if(epoch===this.epoch)this.emit('error',e.message||'请再次点击以开启声音');});}
 continuePending(){if(this.phase!=='waiting')return;this.emit('generating','准备继续播放');this.unlockAndRun();}
}
