import { normalizeRoute } from './routes.js';
import { TTSParameters } from './parameters.js';
import { DEFAULT_FORMAT,DEFAULT_PROMPT,LEGACY_FORMATS,validatePreset,isPlaceholderRole } from './protocol.js';
import { defaultDraw,normalizeDraw,validateDrawPreset } from './draw.js';
import { defaultChat,normalizeChat,validateChatPreset } from './chat.js';
export const NAMESPACE='stTtsDialogue';
export function freshState(){return {version:1,scope:crypto.randomUUID(),enabled:true,theme:'system',general:{defaultLanguage:'zh',voiceEnabled:true,cacheEnabled:true,floatingEnabled:true,waveformEnabled:true},selected:'',activePreset:'default',routes:[],connections:Object.fromEntries(Object.entries(TTSParameters.catalogs).map(([key,c])=>[key,{model:c.model,region:key==='mini'?'cn':undefined,params:TTSParameters.defaults(key),parametersVersion:1}])),presets:[{id:'default',name:'默认双语',format:DEFAULT_FORMAT,injection:{position:'in_chat',depth:0,role:'system'},entries:[{id:'dialogue',title:'台词生成规则',enabled:true,text:DEFAULT_PROMPT}]}],draw:defaultDraw(),chat:defaultChat()};}
export function normalizeSettings(value){const base=freshState();if(!value)return base;const out=structuredClone(value);out.version=1;out.scope=out.scope||base.scope;out.enabled=out.enabled!==false;out.theme=['system','light','dark'].includes(out.theme)?out.theme:'system';out.general={...base.general,...out.general};out.routes=Array.isArray(out.routes)?out.routes.map(normalizeRoute):[];out.draw=normalizeDraw(out.draw);out.chat=normalizeChat(out.chat);for(const r of out.routes)if(r.appearance!==undefined)r.appearance=String(r.appearance).slice(0,2000);out.presets=out.presets?.length?out.presets:base.presets;for(const p of out.presets)if(p.format===LEGACY_FORMATS[0])p.format=DEFAULT_FORMAT;out.activePreset=out.presets.some(p=>p.id===out.activePreset)?out.activePreset:out.presets[0].id;out.selected=out.routes.some(r=>r.id===out.selected)?out.selected:(out.routes[0]?.id||'');out.connections??={};for(const key of Object.keys(base.connections)){out.connections[key]={...base.connections[key],...out.connections[key],params:{...base.connections[key].params,...out.connections[key]?.params}};TTSParameters.normalize(key,out.connections[key]);}for(const p of out.presets){p.injection={...base.presets[0].injection,...p.injection};p.entries??=[{id:crypto.randomUUID(),title:'台词规则',enabled:true,text:p.prompt||''}];}return out;}
export function validateSettings(s){if(JSON.stringify(s).length>2_000_000)throw Error('设置内容过大');if(s.routes.some(r=>!r.name?.trim()||!['fish','mini','eleven'].includes(r.engine)))throw Error('角色配音设置无效');if(new Set(s.routes.map(r=>r.name.trim())).size!==s.routes.length)throw Error('角色名不可重复');for(const p of s.presets)validatePreset(p);if(s.chat){for(const p of s.chat.presets)validateChatPreset(p);if(new Set(s.chat.presets.map(p=>p.id)).size!==s.chat.presets.length||new Set(s.chat.contacts.map(c=>c.name)).size!==s.chat.contacts.length)throw Error('聊天预设 ID 或联系人名字重复');}if(s.draw){for(const p of s.draw.presets)validateDrawPreset(p);if(new Set(s.draw.presets.map(p=>p.id)).size!==s.draw.presets.length||new Set(s.draw.styles.map(p=>p.id)).size!==s.draw.styles.length)throw Error('绘图预设 ID 不可重复');}for(const [key,c] of Object.entries(s.connections)){if(!TTSParameters.catalogs[key])continue;const err=TTSParameters.validate(key,c);if(err)throw Error(TTSParameters.catalogs[key].model+'：'+err);}return s;}
export function modelRules(s){const output=[];const configured=s.routes.filter(r=>!isPlaceholderRole(r.name));const routes=configured.length?configured:[{name:'未配置角色',engine:'fish',model:s.connections.fish.model}];for(const r of routes){const model=r.model||s.connections[r.engine].model;let rule;if(r.engine==='mini'){rule='情绪只能选择 '+TTSParameters.tags('mini',model).join('、')+'。';rule+=model.startsWith('speech-2.8')?'可在原文中使用 (laughs)、(chuckle)、(coughs)、(clear-throat)、(groans)、(breath)、(pant)、(inhale)、(exhale)、(gasps)、(sniffs)、(sighs)、(snorts)、(burps)、(lip-smacking)、(humming)、(hissing)、(emm)、(sneezes)。':'不要使用语气词声音标签。';rule+='停顿写成 <#0.3#> 等（0.01–99.99 秒），放在两段实际说话文字之间，不连续放置。';}else if(r.engine==='eleven'){rule=model.startsWith('eleven_v3')?'情绪字段描述台词情绪；表达控制放原文内，例如 [whispers]、[laughs]、[sighs]、[sad]、[excited]。':'情绪字段保留描述，但原文不加入方括号声音标签。';}else rule=model==='s1'?'情绪字段保留描述；原文可使用圆括号语气标签 (happy)、(sad)、(angry)、(whispering)。':'情绪字段保留描述；原文可使用方括号语气标签 [happy]、[sad]、[angry]、[whispering]。';output.push(JSON.stringify(r.name)+' 使用 '+r.engine+' / '+model+'：'+rule);}return '各说话者的朗读规则（只用于台词，不改变人物设定）：\n'+output.join('\n');}