import {connectBackend} from './backend-client.js';
import {desktopIcon,icon,wave,names} from './icons.js';
import {esc,btn} from './common.js';
import {rolesApp} from './roles.js';
import {enginesApp} from './engines.js';
import {presetsApp} from './presets.js';
import {libraryApp,galleryApp,notesApp,listenApp} from './media-apps.js';
import {settingsApp,wallpapers} from './settings.js';

export function createPhoneApp({window:win,api,mount=win.document.getElementById('root')}){
 const doc=win.document,controller=new win.AbortController(),signal=controller.signal,views=new Map(),assets=new Map();
 const media=win.matchMedia('(prefers-color-scheme: dark)'),motion=win.matchMedia('(prefers-reduced-motion: reduce)');
 let panelVisible=true,active=null,locked=false,sheet=null,disposed=false,preferences=null,appearanceKey='',appearanceEpoch=0,toastTimer,animation,openTimer,playback=api.status();
 mount.innerHTML=`<div class="phone-stage"><div class="stage-bar"><span>ST-TTS · 角色对白</span><div class="stage-actions"><button data-system="help" aria-label="手机界面说明">i</button><button data-system="close" aria-label="返回酒馆">${icon('close')}</button></div></div><div class="device"><button class="power-key" data-system="power" aria-label="锁屏或唤醒"></button><div class="screen" data-view="home"><div class="wallpaper"></div><div class="statusbar"><time data-clock="small"></time><button class="status-icons" data-system="control" aria-label="打开控制中心，或向下拖动"><svg viewBox="0 0 24 20" aria-hidden="true" fill="currentColor"><rect x="3" y="13" width="3" height="5" rx="1"/><rect x="8" y="10" width="3" height="8" rx="1"/><rect x="13" y="6" width="3" height="12" rx="1"/><rect x="18" y="2" width="3" height="16" rx="1"/></svg><svg viewBox="0 0 24 20" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M2 6a16 16 0 0 1 20 0M6 10a10 10 0 0 1 12 0M9 14a5 5 0 0 1 6 0"/><circle cx="12" cy="18" r="1" fill="currentColor"/></svg><span class="battery" aria-hidden="true"></span></button></div><button class="island" data-system="island" aria-label="打开听取"><span class="island-title"></span><span class="island-wave" hidden>${wave}</span><span class="camera"></span></button><main class="home"><div class="clock-block"><p class="home-date" data-clock="date"></p><div class="home-clock" data-clock="large"></div><p class="home-brand">ST-TTS 角色对白</p></div><div class="apps-grid"></div><div class="phone-dock"></div></main><section class="app-frame" hidden><header class="app-nav"><button class="nav-button" data-system="back" aria-label="返回">${icon('back')}</button><h2 data-app-title></h2><button class="nav-button" data-system="home" aria-label="返回桌面">${icon('home')}</button></header><div class="app-content"></div></section><button class="home-indicator" data-system="home" aria-label="返回桌面"></button><section class="lockscreen" role="dialog" aria-modal="true" aria-label="锁屏" hidden>${icon('lock')}<p class="home-date" data-clock="date"></p><div class="home-clock" data-clock="large"></div><div class="control-player"><span>${wave}</span><div><strong data-playing-speaker></strong><small data-playing-message></small></div><button class="nav-button" data-system="toggle" aria-label="暂停或继续">${icon('play')}</button></div><div class="lock-bottom"><button data-system="unlock">上滑或点此进入</button><button data-system="unlock">跳过锁屏</button></div></section><div class="toast" role="status" hidden></div></div></div></div>`;
 const $=s=>mount.querySelector(s),screen=$('.screen'),home=$('.home'),frame=$('.app-frame'),content=$('.app-content'),lockscreen=$('.lockscreen');
 function notify(text){if(disposed)return;const el=$('.toast');el.textContent=text||'操作未完成';el.hidden=false;win.clearTimeout(toastTimer);toastTimer=win.setTimeout(()=>el.hidden=true,4500);}
 function run(fn){try{const result=fn();result?.catch?.(error=>notify(error.message));return result;}catch(error){notify(error.message);}}
 function syncInert(){home.inert=!!active||locked||!!sheet;frame.inert=!active||locked||!!sheet;$('.statusbar').inert=locked||!!sheet;$('.island').inert=locked||!!sheet;$('.home-indicator').inert=locked||!!sheet;lockscreen.inert=!locked||!!sheet;}
 function dialog(title,html){
  sheet?.close(null);const focus=doc.activeElement,overlay=doc.createElement('div');overlay.className='overlay';overlay.innerHTML=`<section class="sheet" role="dialog" aria-modal="true" aria-label="${esc(title)}"><header class="sheet-header"><h2>${esc(title)}</h2><button class="nav-button" data-sheet-close aria-label="关闭">${icon('close')}</button></header><div class="sheet-body">${html}</div></section>`;screen.append(overlay);
  let live=true;const callbacks=[];
  const result={body:overlay.querySelector('.sheet-body'),get live(){return live;},onClose(fn){callbacks.push(fn);},close(value=null){if(!live)return;live=false;overlay.remove();if(sheet===result)sheet=null;syncInert();for(const callback of callbacks)callback(value);if(focus?.isConnected&&!focus.closest('[inert]'))focus.focus({preventScroll:true});}};
  overlay.addEventListener('click',e=>{if(e.target===overlay||e.target.closest('[data-sheet-close]'))result.close(null);});
  overlay.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const controls=[...overlay.querySelectorAll('button,input,select,textarea,a[href]')].filter(el=>!el.disabled&&!el.hidden);if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(e.shiftKey&&doc.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&doc.activeElement===last){e.preventDefault();first.focus();}});
  sheet=result;syncInert();overlay.querySelector('button').focus({preventScroll:true});return result;
 }
 function confirm(title,text=''){return new Promise(resolve=>{const d=dialog(title,`<p class="help-copy">${esc(text)}</p><div class="actions">${btn('cancel','取消')}${btn('confirm','确认','primary')}</div>`);d.onClose(value=>resolve(value===true));d.body.addEventListener('click',e=>{const action=e.target.closest('button')?.dataset.action;if(action==='confirm')d.close(true);if(action==='cancel')d.close(false);});});}
 const help=text=>dialog('说明',`<p class="help-copy">${esc(text)}</p>`);
 const ctx={api,doc,win,notify,dialog,confirm,help,lock,open,visible:name=>active===name&&!locked};
 const factories={roles:rolesApp,engines:enginesApp,presets:presetsApp,library:libraryApp,gallery:galleryApp,notes:notesApp,listen:listenApp,settings:settingsApp};
 function open(name,roleId){
  if(!factories[name])return;sheet?.close(null);unlock();active=name;
  let v=views.get(name);if(!v){v=factories[name](ctx);views.set(name,v);content.append(v.root);}else run(()=>v.refresh());
  for(const [id,view] of views)view.root.hidden=id!==name;
  home.hidden=true;frame.hidden=false;screen.dataset.view='app';$('[data-app-title]').textContent=names[name];
  screen.dataset.opening='true';win.clearTimeout(openTimer);openTimer=win.setTimeout(()=>delete screen.dataset.opening,240);syncInert();$('.app-nav [data-system=back]').focus({preventScroll:true});
  if(roleId&&v.edit)v.edit(roleId);v.onPlayback?.(playback);
 }
 function showHome(){sheet?.close(null);if(locked)return;active=null;home.hidden=false;frame.hidden=true;screen.dataset.view='home';syncInert();}
 function back(){if(sheet){sheet.close(null);return;}if(locked){unlock();return;}if(active&&views.get(active)?.back?.())return;showHome();}
 function lock(){sheet?.close(null);locked=true;lockscreen.hidden=false;syncInert();lockscreen.querySelector('[data-system=unlock]').focus({preventScroll:true});clock();}
 function unlock(){if(!locked)return;locked=false;lockscreen.hidden=true;syncInert();if(active)$('.app-nav [data-system=back]').focus({preventScroll:true});else home.querySelector('button')?.focus({preventScroll:true});}
 function clock(){const now=new Date(),time=now.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}),date=now.toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});for(const el of mount.querySelectorAll('[data-clock]'))el.textContent=el.dataset.clock==='date'?date:time;}
 function theme(){const mode=preferences?.theme||api.getState().theme;doc.documentElement.dataset.theme=mode==='system'?(media.matches?'dark':'light'):mode;}
 const aliases={book:'presets',camera:'gallery',note:'notes',person:'roles',microphone:'engines',headphones:'listen'};
 async function appearance(phone){
  preferences=phone;theme();const key=JSON.stringify([phone.wallpaper,phone.icons,phone.iconStyle]);if(key===appearanceKey)return;const ticket=++appearanceEpoch;
  const photoIds=new Set([phone.wallpaper.kind==='photo'?phone.wallpaper.photoId:null,...Object.values(phone.icons).filter(x=>x.kind==='photo').map(x=>x.photoId)].filter(Boolean));
  const records=await Promise.all([...photoIds].map(async id=>[id,await api.getPhoto(id)]));if(disposed||ticket!==appearanceEpoch)return;
  for(const url of assets.values())win.URL.revokeObjectURL(url);assets.clear();for(const [id,record] of records)if(record)assets.set(id,win.URL.createObjectURL(record.blob));
  const wall=phone.wallpaper.kind==='builtin'?wallpapers[phone.wallpaper.key]||wallpapers.sky:null,photo=assets.get(phone.wallpaper.photoId);
  screen.style.setProperty('--wall',photo?`linear-gradient(#ffffff18,#ffffff18),url("${photo}")`:wall?.background||wallpapers.sky.background);screen.style.setProperty('--wall-ink',photo?'#fff':wall?.ink||wallpapers.sky.ink);home.style.textShadow=photo?'0 1px 7px #000,0 1px 3px #000':'none';screen.dataset.iconStyle=phone.iconStyle;
  function appIcon(id){const custom=phone.icons[id],image=custom?.kind==='photo'?assets.get(custom.photoId):null,glyph=custom?.kind==='glyph'&&custom.key!=='default'?custom.key:id;const art=image?`<img src="${esc(image)}" alt="">`:names[glyph]||aliases[glyph]?desktopIcon(aliases[glyph]||glyph):glyph==='wave'?wave:icon(glyph);return `<button class="app-icon" data-app="${id}"><span class="icon-tile">${art}</span><span class="app-label">${names[id]}</span></button>`;}
  $('.apps-grid').innerHTML=['roles','engines','presets','library','gallery','notes'].map(appIcon).join('');$('.phone-dock').innerHTML=['listen','settings'].map(appIcon).join('');appearanceKey=key;
 }
 function animate(){win.cancelAnimationFrame(animation);for(const bar of mount.querySelectorAll('.wave i'))bar.style.removeProperty('transform');if(disposed||!panelVisible||doc.hidden||motion.matches||playback.phase!=='playing'||!api.getState().general.waveformEnabled)return;let before=0;const draw=time=>{if(time-before>32){const levels=api.levels();for(const [i,bar] of [...mount.querySelectorAll('.island-wave .wave i,.play-card>.wave i,.control-player .wave i,[data-state=playing] .wave i')].entries())bar.style.transform='scaleY('+(.2+.8*(levels[i%5]||0))+')';before=time;}animation=win.requestAnimationFrame(draw);};animation=win.requestAnimationFrame(draw);}
 function paintPlayback(state){playback=state;const activeSound=['playing','paused','generating','waiting'].includes(state.phase);$('.island-title').textContent=activeSound?(state.speaker||'听取'):'';$('.island-wave').hidden=!activeSound;$('.island .camera').hidden=activeSound;$('.island').setAttribute('aria-label',activeSound?'查看 '+state.speaker+' 的播放状态':'打开听取');for(const el of mount.querySelectorAll('[data-playing-speaker]'))el.textContent=state.speaker||'等待播放';for(const el of mount.querySelectorAll('[data-playing-message]'))el.textContent=state.message||'点击台词开始';for(const el of mount.querySelectorAll('[data-system=toggle]')){el.innerHTML=icon(state.phase==='paused'?'play':'pause');el.disabled=!['playing','paused','generating'].includes(state.phase);}
  for(const v of views.values())v.onPlayback?.(state);animate();
 }
 function control(){
  const s=api.getState(),p=preferences||{volume:api.getVolume(),theme:s.theme};const d=dialog('控制中心',`<div class="control-player">${wave}<div><strong data-playing-speaker></strong><small data-playing-message></small></div><button class="nav-button" data-system="toggle" aria-label="暂停或继续">${icon('play')}</button></div><div class="group pad"><div class="meter-label"><span>播放音量</span><output>${Math.round(p.volume*100)}%</output></div><input class="slider" data-control="volume" type="range" min="0" max="100" value="${Math.round(p.volume*100)}" aria-label="播放音量"></div><div class="control-tiles"><button class="control-tile" data-control="floating" aria-pressed="${s.general.floatingEnabled}">${icon('home')}悬浮入口 · ${s.general.floatingEnabled?'开':'关'}</button><button class="control-tile" data-system="power">${icon('lock')}锁屏</button></div><div class="segmented">${[['system','系统'],['light','日间'],['dark','夜间']].map(([key,label])=>`<button data-theme="${key}" aria-pressed="${p.theme===key}">${label}</button>`).join('')}</div><div class="actions">${btn('stop','停止播放')}${btn('listen','打开听取')}</div>`);
  d.body.addEventListener('input',e=>{if(e.target.dataset.control==='volume')d.body.querySelector('output').textContent=e.target.value+'%';});
  d.body.addEventListener('change',e=>{if(e.target.dataset.control==='volume')run(()=>api.setVolume(Number(e.target.value)/100));});
  d.body.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;run(async()=>{if(el.dataset.theme){await api.savePhone({theme:el.dataset.theme});if(d.live)for(const b of d.body.querySelectorAll('[data-theme]'))b.setAttribute('aria-pressed',String(b===el));}if(el.dataset.control==='floating'){const enabled=!api.getState().general.floatingEnabled;api.updateGeneral({floatingEnabled:enabled});el.setAttribute('aria-pressed',String(enabled));el.innerHTML=icon('home')+'悬浮入口 · '+(enabled?'开':'关');}if(el.dataset.action==='stop')api.stop();if(el.dataset.action==='listen')open('listen');});});paintPlayback(playback);
 }
 mount.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||b.disabled)return;if(b.dataset.app){open(b.dataset.app);return;}if(!b.dataset.system)return;run(()=>{switch(b.dataset.system){case 'close':api.close();break;case 'home':showHome();break;case 'back':back();break;case 'power':locked?unlock():lock();break;case 'unlock':unlock();break;case 'island':open('listen');break;case 'control':control();break;case 'toggle':api.toggle();break;case 'help':help('桌面图标打开对应应用；底部横条回桌面。\n右上角可点开或向下拉出控制中心。侧键可查看锁屏，锁屏随时跳过。\n\n信号与电量图标为装饰。语音只在点击台词、播放或试听时生成。');break;}});},{signal});
 let drag=null;
 mount.addEventListener('pointerdown',e=>{const zone=e.target.closest('.status-icons,.lockscreen');if(!zone||drag||e.button!==0)return;drag={id:e.pointerId,y:e.clientY,x:e.clientX,lock:zone===lockscreen};},{signal});
 mount.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;drag=null;const dy=e.clientY-d.y;if(Math.abs(e.clientX-d.x)>70)return;if(d.lock&&dy< -45)unlock();else if(!d.lock&&dy>45)control();},{signal});
 mount.addEventListener('pointercancel',()=>drag=null,{signal});
 doc.addEventListener('keydown',e=>{doc.documentElement.dataset.keyboard='true';if(e.key==='Escape'){e.preventDefault();if(sheet||locked||active)back();else api.close();}if(locked&&e.key==='Tab'){const focusable=[...lockscreen.querySelectorAll('button')].filter(el=>!el.disabled),first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&doc.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&doc.activeElement===last){e.preventDefault();first.focus();}}},{signal});
 doc.addEventListener('pointerdown',()=>delete doc.documentElement.dataset.keyboard,{signal});doc.addEventListener('visibilitychange',animate,{signal});media.addEventListener('change',theme,{signal});motion.addEventListener('change',animate,{signal});
 const unsubscribe=api.subscribe(event=>{if(disposed)return;if(event.type==='playback')paintPlayback(event);if(event.type==='settings'){theme();animate();}if(event.type==='phone')run(()=>appearance(event.preferences));if(event.type==='library'){const key=({favorites:'library',cache:'library',photos:'gallery',notes:'notes'})[event.collection];if(active===key)run(()=>views.get(key)?.refresh());}if(event.type==='audio-ready'){views.get('listen')?.onPlayback?.(api.status());}});
 const previousOpenRole=win.stTtsOpenRole,previousVisibility=win.stTtsPanelVisibility;win.stTtsOpenRole=id=>open('roles',id);
 win.stTtsPanelVisibility=visible=>{panelVisible=visible;if(!visible)sheet?.close(null);else if(preferences?.lockOnOpen&&!api.pendingRole())lock();animate();};
 function dispose(){if(disposed)return;disposed=true;appearanceEpoch++;unsubscribe();controller.abort();sheet?.close(null);for(const v of views.values())v.dispose();for(const url of assets.values())win.URL.revokeObjectURL(url);assets.clear();win.clearInterval(clockTimer);win.clearTimeout(toastTimer);win.clearTimeout(openTimer);win.cancelAnimationFrame(animation);win.stTtsOpenRole=previousOpenRole;win.stTtsPanelVisibility=previousVisibility;}
 win.addEventListener('pagehide',dispose,{signal});clock();const clockTimer=win.setInterval(clock,15000);
 const ready=api.getPhone().then(async p=>{if(disposed)return;await appearance(p);if(disposed)return;const pending=api.pendingRole();if(pending){const r=api.getState().routes.find(r=>r.name===pending);open('roles',r?.id);}else if(p.lockOnOpen)lock();}).catch(error=>{if(disposed)return;notify(error.message);return appearance({wallpaper:{kind:'builtin',key:'sky'},icons:{},iconStyle:'color',lockOnOpen:false,volume:api.getVolume(),theme:api.getState().theme});});
 return {ready,open,home:showHome,back,lock,unlock,dispose,views,get active(){return active;},get locked(){return locked;}};
}
if(typeof window!=='undefined'&&window.document.getElementById('root')){
 try{window.stTtsPhone=createPhoneApp({window,api:connectBackend()});}
 catch(error){const el=window.document.querySelector('.startup');if(el){el.textContent=error.message;el.setAttribute('role','alert');}}
}